# Site settings
title: Fredrik!
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  exitin _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fredriko83
github_username:  fredriko83

# Build settings
markdown: kramdown
