# Site settings
title: Fredrik Olsson
email: fredriko.olsson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Fredriks blogg and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fredriko83.github.io" # the base hostname & protocol for your site
twitter_username: fredriko83
github_username:  fredriko83

# Build settings
markdown: kramdown
